[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false
  network = "web"

[providers.file]
  filename = "traefik_dynamic.toml"
